# Generated by Django 5.2.6 on 2025-09-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesCLDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('subordinacao', models.CharField(choices=[('PR', 'Presidência'), ('VC', 'Vice-Presidência'), ('1S', 'Primeira Secretaria'), ('2S', 'Segunda Secretaria'), ('3S', 'Terceira Secretaria')], default='1S', max_length=2, verbose_name='Unidade da mesa')),
            ],
            options={
                'verbose_name': 'Unidade da CLDF',
                'verbose_name_plural': 'Unidades da CLDF',
            },
        ),
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estagiario', models.CharField(max_length=200, verbose_name='Nome')),
                ('fone', models.CharField(max_length=40, verbose_name='Fone(s)')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('grau', models.CharField(max_length=2, verbose_name='Nível')),
                ('unidade_cldf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagiarios.unidadescldf')),
            ],
            options={
                'verbose_name': 'Estagiário',
                'verbose_name_plural': 'Estagiários',
            },
        ),
    ]
