# Generated by Django 5.2.6 on 2025-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='grau',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='nivel',
            field=models.CharField(choices=[('2G', 'Segundo Grau'), ('SP', 'Superior')], default='1G', max_length=2, verbose_name='Nível'),
            preserve_default=False,
        ),
    ]
