# Generated by Django 5.2.6 on 2025-09-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiarios', '0002_remove_estagiario_grau_estagiario_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescldf',
            name='sigla',
            field=models.CharField(default='', max_length=15, verbose_name='Sigla'),
            preserve_default=False,
        ),
    ]
