# Generated by Django 5.2.6 on 2025-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiarios', '0003_unidadescldf_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='data_inicio',
            field=models.DateField(default='2025-09-15', verbose_name='Data início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estagiario',
            name='matricula',
            field=models.IntegerField(default=0, verbose_name='Matrícula'),
            preserve_default=False,
        ),
    ]
