# Generated by Django 5.2.6 on 2025-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiarios', '0004_estagiario_data_inicio_estagiario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='duracao_estagio',
            field=models.IntegerField(default=6, verbose_name='Duração (em meses)'),
        ),
    ]
